### ISSUE TITLE
Event Signups not working

### ISSUE THREAD

**Issue by alexbabington** [backstage-technical-services/hub#136] opened 2022-03-20 15:56 UTC
#### Summary

Crew volunteer not volunteering or double volunteering

#### Actual behaviour

Instance 1: Logged in and tried to volunteer for polesoc. Website showed the "volunteered" / "unvolunteered" pop up green box and sent an email to the TEM and myself. However, it did not add me or remove me from the crew list or add the event under my events

Instance 2: Volunteering for ChaOS Formal Recital: The website signed me up to the crewlist twice and emailed myself / the TEM twice.

Have checked both on opera (chromium fork) and firefox and they experience the same behaviour. Instance 1 worked when the TEM signed me up.

#### Expected behaviour

Add 1 instance of me to the crewlist, add the event under my events, email the TEM and myself once.

#### Steps to reproduce

Log in, navigate to the event page, click volunteer

#### When did it happen?

15:50 UTC on 20/3/2022

#### Urgency

High - Event signups are a core feature of the website.

**Comment by bnjns** [comment] 2022-03-22 21:17
This is probably a duplicate of #135?

**Comment by bnjns** [comment] 2022-03-22 21:59
Yeah there's something weird going on - I'd like to move any conversation on this bug into #135 as I think they're basically the same underlying issue.

**Closed** 2022-03-22 23:16 UTC
Labels: duplicate, type/bug
